export const EN = {
    type: "EN",
    email: "Email address",
    password: "Password",
    confirmpass: "Password confirm",
    profile: {
        logout: "Log out",
        welcome: "Welcome",
        ethaddress: "ETH address",
        controlPanel: {
            dashboard: "Dashboard",
            title1: "Purchased tokens",
            text1: "We will distribute the tokens to participants 10 days after the end of Token Sale. Please configure your ETH (ERC20) wallet in order to receive purchased tokens.",
            configure: "Configure",
            title2: "Affiliate Program",
            text2: "Share your affiliate link and earn 10% in ETH on every purchase for the users that you refer.\nNote that the commission will be ready for withdraw only after the token sale ends.",
            affiliatelink: "Affliliate link",
            registrations: "Registrations",
            commission: "Commision (USD)",
        },
        settings: {
            settings: "Settings",
            ethaddress: "Ethereum address",
            profile: "Profile",
            text1: "Please make sure that you own the private key for your ETH address. Our token is 100% compatible with wallet MyEtherWallet.com, Metamask or Mist.\n\n Note: Please do not use deposit addresses from exchanges.",
            save: "Save",
            update: "Update",
            email: "Email address",
            changepass: "Change password",
        }
    },
    login: {
        title: "Login",
        notmember: "Not a member yet ?",
        forgotpass: "Forgot my password",
    },
    account: {
        terms: "Token terms",
        whitepaper: "White Paper",
    },
    forgotpass: {
        title: "Recover password",
        send: "Send reset link",
    },
    register: {
        title: "Account Register",
        check1: "I certify that the beneficial owner is not a citizen of USA, China and Hong Kong",
        check2: "I agree to the",
        send: "Submit",
        gotologin: "Go to account login",
    },
    firsthome: {
        title1: "Join the blockchain DApps movement",
        title2: "The world's first software development platform offering microservices for the blockchain to build decentralized serverless applications",
        doc1: "White paper",
        doc2: "Token terms",
        status1: "WORKING MVP",
        status2: "STABLE RELEASE",
        status3: "3 YEARS OLD",
        status4: "75000+ MONTHLY DOWNLOADS",
    },
    clock: {
        title: "Token sale start",
        register: "Register now",
        price: "Token price",
        min: "Minimum purchase",
        d: "d",
        h: "h",
        m: "m",
        s: "s",
        contact: "For private sales and other inquiries please contact us at",
        contacturl: "info@squeezer.io",
    },
    lang: {
        EN: "english",
        UA: "ukrainian",
        RU: "russian",
    }
}

export const UA = {
    type: "UA",
    email: "Email",
    password: "Password",
    confirmpass: "Password confirm",
    profile: {
        logout: "Log out",
        welcome: "Welcome",
        ethaddress: "ETH address",
        controlPanel: {
            dashboard: "Dashboard",
            title1: "Purchased tokens:",
            text1: "We will distribute the tokens to participants 10 days after the end of Token Sale. Please configure your ETH (ERC20) wallet in order to receive purchased tokens.",
            configure: "Configure",
            title2: "Affiliate Program",
            text2: "Share your affiliate link and earn 10% in ETH on every purchase for the users that you refer.\nNote that the commission will be ready for withdraw only after the token sale ends.",
            affiliatelink: "Affliliate link",
            registrations: "Registrations",
            commision: "Commision (USD)",
        },
        settings: {
            settings: "Settings",
            ethaddress: "Ethereum address",
            profile: "Profile",
            text1: "Please make sure that you own the private key for your ETH address. Our token is 100% compatible with wallet MyEtherWallet.com, Metamask or Mist.\n\n Note: Please do not use deposit addresses from exchanges.",
            save: "Save",
            update: "Update",
            email: "Email address",
            changepass: "Change password",
        }
    },
    login: {
        title: "Login",
        notmember: "Not a member yet ?",
        forgotpass: "Forgot my password",
    },
    account: {
        terms: "Token terms",
        whitepaper: "White Paper",
    },
    forgotpass: {
        title: "Recover password",
        send: "Send reset link",
    },
    register: {
        title: "Account Register",
        check1: "I certify that the beneficial owner is not a citizen of USA, China and Hong Kong",
        check2: "I agree to the",
        send: "Submit",
        gotologin: "Go to account login",
    },
    firsthome: {
        title1: "Join the blockchain DApps movement",
        title2: "The world's first software development platform offering microservices for the blockchain to build decentralized serverless applications",
        doc1: "White paper",
        doc2: "Token terms",
        status1: "WORKING MVP",
        status2: "STABLE RELEASE",
        status3: "3 YEARS OLD",
        status4: "75000+ MONTHLY DOWNLOADS",
    },
    clock: {
        title: "Token sale start",
        register: "Register now",
        price: "Token price",
        min: "Minimum purchase",
        d: "d",
        h: "h",
        m: "m",
        s: "s",
        contact: "For private sales and other inquiries please contact us at",
        contacturl: "info@squeezer.io",
    },
    lang: {
        EN: "english",
        UA: "ukrainian",
        RU: "russian",
    }
}

export const RU = {
    type: "RU",
    email: "Адрес электронной почты",
    password: "Пароль",
    confirmpass: "Подтверджение пароля",
    profile: {
        logout: "Выйти",
        welcome: "Добро пожаловать",
        ethaddress: "Адрес ETH",
        controlPanel: {
            dashboard: "Панель управления",
            title1: "Приобретенные токены",
            text1: "Мы выдадим токены участникам на протяжении 10 дней спустя завершения Распродажи Токенов. Пожалуйста, измените настройки своего кошелька ETH (ERC20) для получения приобретенных токенов.",
            configure: "Настройка",
            title2: "Партнерская программа",
            text2: "Поделитесь вашей партнерской ссылкой и заработайте 10% в ETH на каждой покупке для пользователей, на которых вы ссылаетесь.\nОбратите внимание, что комиссия будет готова для снятия только после завершения продажи токенов.",
            affiliatelink: "Партнерская ссылка",
            registrations: "Регистрация",
            commission: "Комиссия (долл. США)",
        },
        settings: {
            settings: "Настройки",
            ethaddress: "Адрес Ethereum",
            profile: "Профиль",
            text1: "Пожалуйста, убедитесь, что у вас есть личный ключ к вашему адресу ETH. Наш токен полностью совместим с кошельками MyEtherWallet.com, Metamask или Mist.\n\nПримечание: Пожалуйста, не используйте депозитные адреса для обменных операций.",
            save: "Сохранить",
            update: "Обновить",
            email: "Адрес электронной почты",
            changepass: "Сменить пароль",
        }
    },
    login: {
        title: "Вход",
        notmember: "Еще не являетесь членом?",
        forgotpass: "Забыл свой пароль",
    },
    account: {
        terms: "Условия для токенов",
        whitepaper: "Белая книга",
    },
    forgotpass: {
        title: "Восстановить пароль",
        send: "Отправить ссылку для востановления",
    },
    register: {
        title: "Реестр счета",
        check1: "Я подтверждаю, что бенефициарный владелец не является гражданином США, Китая и Гонконга",
        check2: "Я принимаю",
        send: "Отправить",
        gotologin: "Перейти ко входу в учетную запись",
    },
    firsthome: {
        title1: "ПРИСОЕДИНЯЙТЕСЬ К РЕВОЛЮЦИИ БЛОКЧЕЙН-ПРИЛОЖЕНИЙ",
        title2: "Первая в мире платформа для разработки ПО, предлагающая микроуслуги для блокчейн",
        doc1: "Белая бумага",
        doc2: "Условия для токенов",
        status1: "WORKING MVP",
        status2: "STABLE RELEASE",
        status3: "3 YEARS OLD",
        status4: "75000+ MONTHLY DOWNLOADS",
    },
    clock: {
        title: "Розпродажа токенов",
        register: "Зарегистрироваться сейчас",
        price: "Цена токена",
        min: "Минимальная покупка",
        d: "д",
        h: "ч",
        m: "м",
        s: "с",
        contact: "Для частных продаж и других запросов, пожалуйста, свяжитесь с нами по адресу",
        contacturl: "info@squeezer.io",
    },
    lang: {
        EN: "английский",
        UA: "украинский",
        RU: "русский",
    }
}