export const EN = {
    type: "EN",
    email: "Email address",
    password: "Password",
    confirmpass: "Password confirm",
    send: "Send",
    profile: {
        logout: "Log out",
        welcome: "Welcome",
        ethaddress: "ETH address",
        controlPanel: {
            dashboard: "Dashboard",
            title1: "Purchased tokens",
            text1: "We will distribute the tokens to participants 10 days after the end of Token Sale. Please configure your ETH (ERC20) wallet in order to receive purchased tokens.",
            configure: "Configure",
            title2: "Affiliate Program",
            text2: "Share your affiliate link and earn 10% in ETH on every purchase for the users that you refer.\nNote that the commission will be ready for withdraw only after the token sale ends.",
            affiliatelink: "Affliliate link",
            registrations: "Registrations",
            commission: "Commision (USD)",
        },
        settings: {
            settings: "Settings",
            ethaddress: "Ethereum address",
            profile: "Profile",
            text1: "Please make sure that you own the private key for your ETH address. Our token is 100% compatible with wallet MyEtherWallet.com, Metamask or Mist.\n\n Note: Please do not use deposit addresses from exchanges.",
            save: "Save",
            update: "Update",
            email: "Email address",
            changepass: "Change password",
        },
        letterWarn1: "Your email",
        letterWarn2: "isn't verificate. Please, click to send a letter.",
        letterSucc: "Letter is send to your email",
    },
    login: {
        title: "Login",
        notmember: "Not a member yet ?",
        forgotpass: "Forgot my password",
    },
    account: {
        terms: "Token terms",
        whitepaper: "White Paper",
    },
    forgotpass: {
        title: "Recover password",
        send: "Send reset link",
        newpass: "New password",
    },
    register: {
        title: "Account Register",
        check1: "I certify that the beneficial owner is not a citizen of USA, China and Hong Kong",
        check2: "I agree to the",
        send: "Submit",
        gotologin: "Go to account login",
    },
    firsthome: {
        title1: "Join the blockchain DApps movement",
        title2: "The world's first software development platform offering microservices for the blockchain to build decentralized serverless applications",
        doc1: "White paper",
        doc2: "Token terms",
        status1: "WORKING MVP",
        status2: "STABLE RELEASE",
        status3: "3 YEARS OLD",
        status4: "75000+ MONTHLY DOWNLOADS",
    },
    clock: {
        title: "Token sale start",
        register: "Register now",
        price: "Token price",
        min: "Minimum purchase",
        d: "d",
        h: "h",
        m: "m",
        s: "s",
        contact: "For private sales and other inquiries please contact us at",
        contacturl: "info@squeezer.io",
    },
    lang: {
        EN: "english",
        UA: "ukrainian",
        RU: "russian",
    },
    header: {
        warning: "IMPORTANT! Our website is the only platform authorized to sell SQR tokens. We will never use Telegram Messenger or other channels to conduct sales.",
        account: "My Account",
        solution: "Solution",
        features: "Features",
        token: "Token",
        roadmap: "Roadmap",
        team: "Team",
        careers: "Careers",
        mvp: "MVP",
    },
    quote: {
        text: "Business and technical consulting firms are looking for opportunities to dive into the blockchain world. Squeezer is the most cost efficient and accessible way to do it.",
        writer: "Jeffrey Liu, Technical Advisor",
    },
    benefits: {
        topik1span: "Issues ",
        topik1: "when building blockchain apps",
        text1: "Setting up a blockchain development environment is time-consuming, and it is difficult to maintain stability for post-production releases.",
        text2: "Thousands of new blockchain transactions will generally crash a user's back end system.",
        text3: "Software developers new to blockchain technology have to familiarize themselves with the genesis block code and create complex parsers before building blockchain apps.",
        topik2span: "Squeezer's",
        topik2: "solution",
        text4: "Create a single unified blockchain connector that will allow developers to connect to any blockchain (such as BTC, ETH, or LTC) and use a sandbox to test the apps.",
        text5: "Squeezer apps are powered by microservices, which means that the auto-scalability feature is enabled by default. Microservices also support auto-healing and allow for silent cloud deployments.",
        text6: "The Squeezer Platform will compile and deploy apps in multiple stages directly from GitHub or other code repositories.",
    },
    capabilities: {
        maintexthead: "Main features of Squeezer",
        maintext: "Squeezer is a platform that helps software developers build apps easily without tackling the entire blockchain infrastructure. It is also a powerful tool for providing high-quality blockchain software components to large enterprise organizations. Squeezer uses world-class microservices platforms, such as AWS Lambda, Google Functions, and Azure Functions.",
        tip1head: "Zero administration",
        tip1text: "Deploy your code without any lengthy set-up beforehand or anything to manage afterward.",
        tip2head: "Auto-scaling",
        tip2text: "Let your service providers manage the scaling challenges. No need to set alerts or write scripts to scale up or down. Have absolute peace of mind during periods of high or low traffic.",
        tip3head: "Pay-per-use",
        tip3text: "Function-as-a-service (FaaS) compute and managed services charged based on usage rather than pre-provisioned capacity. You can utilize all your resources without paying a cent for idle time.",
        tip4head: "Development climate",
        tip4text: "Simulate the cloud provider environment on your local machine. No need to deploy code at every iteration. Speed up the entire development cycle by 10x.",
        tip5head: "Blockchain",
        tip5text: "A truly revolutionary framework, Squeezer is the first platform that merges the power of microservices with the immutability of blockchain technology.",
        tip6head: "Token",
        tip6text: "The Squeezer Token (SQR) is the core utility used by developers to build and deploy apps on the Squeezer Platform.",
    },
    facts: {
        fact1articl: "More than 75,000 monthly\n downloads",
        fact1text: "Our framework has received a lot\n of favorable attention on NPM, \none of the top software registries.",
        fact2articl: "More than 7000 exchanges",
        fact2text: "Our scalable solution will enable\nexchanges to support high\nvolume transactions.",
        fact3articl: "More than 40 million\ndevelopers targeted",
        fact3text: "Many software developers are\nentering the blockchain\ntechnology space every day. We\nintend to make their experience\nas simple and seamless as\npossible.",
    },
    connector: {
        artikle: "Squeezer Blockchain Connector",
        text: "Our solution is to create a simple interface that will enable software developers to conduct blockchain transactions without having to deal with the blockchain genesis code or create complex components.",
        link: "Source code on GitHub",
    },
    tokens: {
        artikle: "Squeezer Token",
        text1: "The Squeezer Platform is powered by the SQR token. Developers will purchase platform subscriptions with the token to create their applications. Additionally, all consultancy services provided by the Squeezer team will be paid for in SQR tokens.",
        text2: "Every 6 months, we will use 25% of our profits to buy back SQR and destroy them, until we buy 40% of all the SQR back.",
    },
    tokeninfo: {
        head: "Token details",
        infoelementfirstTicker: "Ticker",
        infoelementfirstPrice: "Price",
        infoelementfirstSoftcap: "Soft cap",
        infoelementfirstHardcap: "Hard cap",

        infoelementsecondPresale: "Pre-sale",
        infoelementsecondPresaletext: "May 1, 2018 - May 12, 2018",
        infoelementsecondTarget: "Target",

        infoelementthirdTokensale: "Token sale",
        infoelementthirdTokensaletext: "June 20, 2018 - June 30, 2018",
        infoelementthirdTarget: "Target",

        infoelementthirdCompatibility: "Compatibility",
        infoelementthirdUsage: "Usage",
        infoelementthirdUsagetext: "Platform subscriptions; consultancy services",
        infoelementthirdTokendeliverydate: "Token delivery date",
        infoelementthirdTokendeliverydatetext: "10 days after the token sale ends\nAt the end of the token sale, all unsold tokens will be burned.",

        distributionhead: "Token distribution",
        distribution1article: "Token sale:",
        distribution1text: "75,000,000 SQR (40%) At the end of the token sale, all unsold tokens will be burned.",
        distribution2article: "The Squeezer Platform:",
        distribution2text: "56,250,000 SQR (30%) The reserve required to ensure the operation of the platform. Locked in smart contract with sale restrictions for 12 months.",
        distribution3article: "Team:",
        distribution3text: "37,500,000 SQR (20%) Locked in smart contract with sale restrictions for 24 months.",
        distribution4article: "Advisors:",
        distribution4text: "9,375,000 SQR (5%) Locked in smart contract with sale restrictions for 24 months.",
        distribution5article: "Marketing & partners:",
        distribution5text: "9,375,000 SQR (5%)",

        incomehead: "",
        incometext1: "Technical development:",
        incometext2: "Non-technical staff:",
        incometext3: "Marketing expenses:",
        incometext4: "Infrastructure expenses:",
        incometext5: "Other operating expenses:",
    },
    smart: {
        artikle: "SMART CONTRACT",
        link1: "Source code on GitHub",
        link2: "Information on Etherscan.io",
    },
    roadmap: {
        head: "Roadmap",
        roadmapdata1: "February 2016",
        roadmapgoal1: "Create framework principles and add base functionality",
        roadmapdata2: "September 2016",
        roadmapgoal2: "Proof-of-Concept and plugins integration",
        roadmapdata3: "October 2017",
        roadmapgoal3: "Stable version and cloud providers",
        roadmapdata4: "May 2018",
        roadmapgoal4: "Token pre-sale crowdfunding stage",
        roadmapdata5: "June 2018",
        roadmapgoal5: "Public token sale",
        roadmapdata6: "July 2018",
        roadmapgoal6: "Hire additional developers to build the blockchain cloud connectors",
        roadmapdata7: "February 2019",
        roadmapgoal7: "Deliver the final version of blockchain connector and the Squeezer Platform",
        roadmapdata8: "April 2019",
        roadmapgoal8: "Enable subscription purchases with the SQR token. Start to build apps connected to the blockchain",
    },
    team: {
        head1: "Advisors",
        head2: "The Squeezer Team",
    },
    media: {
        head: "Media",
    },
    clients: {
        head: "Partners & clients",
    },
    share: {
        Sharetext: "Join our Affiliate Program today and earn 10% in ETH commission",
        Sharelink: "Join now",
    },
    questions: {
        head: "Frequently Asked Questions",
        FAQ1: "What is the utility of the SQR token within the Squeezer platform?",
        FAQanswer1: "The SQR token is the fuel that will power our platform. Developers will use the tokens to compile and deploy blockchain applications. Additionally, all the consultancy services on the Squeezer platform will be paid for in SQR tokens",
        FAQ2: "How is blockchain technology integrated with your product?",
        FAQanswer2: "In order to connect microservices to the blockchain, we are building an agnostic connector, a module which will be used by applications to read and write blockchain transactions or trigger other blockchain features, such as smart contracts.",
        FAQ3: "Do you have the required skills to deliver on the roadmap?",
        FAQanswer3: "Our CEO, Nick Chisiu, specializes in microservices. He has successfully completed multiple projects in this field working for top 1000 US INC. Additionally, he has worked as a blockchain consultant for a number of years. He will lead the development team to ensure that we deliver on our promises.",
        FAQ4: "Do you currently have a working product (MVP)?",
        FAQanswer4: "Yes. We have already built the framework of our platform, which will serve as the fundamental tool that developers use to create, build, compile, and deploy their projects. The blockchain connector will soon be attached to the framework in a user-friendly configuration so that it will be as accessible to developers as possible. We invite you to try it out! You will soon see how straightforward it is to create and run a Squeezer project on your local machine. Just go to https://squeezer.io/docs/getting-started",
        link: "For any inquiries or questions regarding our token sale please contact us at",
    },
    endregister: {
        head1: "Don't miss the latest news and updates",
        head2: "Join the blockchain DApps movement",
        button: "Subscribe",
        text1: "Token sale API is fully provided by the Squeezer Framework",
        text2: "The world's first software development platform offering microservices for the blockchain to build decentralized serverless applications",
        link1: "Sign in",
        link2: "Register",

        rejecthead: "Disclaimer",
        rejecttext1: "The tokens do not represent equity, shares, units, royalties or rights to capital, profit or income in the platform or software or in the entity that issues tokens or any other company or intellectual property associated with the platform or any other public or private enterprise, corporation, foundation or other entity in any jurisdiction.",
        rejecttext2: "By offering information, products or services via this website, no solicitation is made by us to any person to use such information, products or services in any jurisdiction where the provision of such information, products or services may be prohibited by law.",
        rejecttext3: "All information presented on this website is for informational purposes only, and is subject to change without notice. This website is not intended to be investment advice, or an offer or solicitation for the purchase or sale of any financial instrument or product.",
        rejecttext4: "The Squeezer token sale implies and relates to the development and use of bleeding-edge and new experimental technologies that may not turn out as expected or be delivered for completion as specified in the whitepaper.",

        footertip1: "© 2018 Squeezer",
        footertip2: "White paper",
        footertip3: "Token terms",
        footertip4: "Golden Data INC, New Horizon, Ground Floor, 3 1⁄2 Miles Philip S.W. Goldson Highway, Belize City, Belize",
    },
    errors: {
        Empty_Email: "Email is empty",
        Empty_Password: "Password is empty",
        Password_Not_Confirmed: "Password not confirmed",
        Empty_Address: "Empty address",
        Auth_Fail: "Authorization is failed",
        Wrong_Email_Password: "Wrong email or password",
        Bad_Request: "No internet connection",
        Email_In_Use: "Email is already used",
        Not_Authorize: "You are not authorize",
        No_Empty_Strings: "One of strings must be not empty",
        Check1: "Please certify that the beneficial owner is not a citizen of USA, China and Hong Kong",
        Check2: "Please agree with the Token terms",
        Email_Invalid: "Email format is invalid",
        Pass_To_Short: "Password must have more than 5 symbols",
        Pass_Invalid: "Password must contain at 3 of 4 of the following: upper case (A-Z), lower case (a-z), number (0-9) and special character (e.g. !@#$%^&*)",
        Email_Already_Verificate: "Email already verificate",
        User_Dont_Exist: "This user don't exist",
        Error_Send: "Error send letter try again",
        Email_Dont_Exist: "This email don't used",
        Password_In_Use: "This is old password",
        Reset_Not_Auth: "Time of letter link is over. Please, send new letter",
        Letter_Error: "Please, try again",
    },
    success: {
        Success_Update: "Update is successful",
        Success_Eth: "Etherium address is successful update",
        Success_Reset: "Reset password is successfull. Now, you can",
        Success_Reset_Login: "login",
        Success_Send_Reset: "Letter for reset password is send",
        Success_Verify1: "Your email",
        Success_Verify2: "is verificate",
        Success_Send_Verify: "Letter is send to your email",
    }
}

export const UA = {
    type: "UA",
    email: "Адреса електронної пошти",
    password: "Пароль",
    confirmpass: "Підтвердження пароля",
    send: "Відправити",
    profile: {
        logout: "Вийти",
        welcome: "Ласкаво просимо",
        ethaddress: "Адреса ETH",
        controlPanel: {
            dashboard: "Панель управління",
            title1: "Придбані токени:",
            text1: "Ми видамо токени учасникам протягом 10 днів після завершення Розпродажі токенів. Будь ласка, змініть налаштування свого гаманця ETH (ERC20) для отримання придбаних токенів.",
            configure: "Налаштування",
            title2: "Партнерская программа",
            text2: "Поділіться вошим партнерським посиланням та отримайте 10% в ETH на кожній покупці від користувачів ,що використали ваше посилання.\nЗверніть увагу що комісія буде доступна для зняття тільки після завершення продажі токенів.",
            affiliatelink: "Партнерське посилання",
            registrations: "Реєстрація",
            commision: "Комісія (долл. США)",
        },
        settings: {
            settings: "Налаштування",
            ethaddress: "Адреса Ethereum",
            profile: "Профіль",
            text1: "Будьласка переконайтесь шо у вас є персональний ключ до вашої адреси ETH. Наш токен повність сумісний з гаманцями MyEtherWallet.com, Metamask або Mist.\n\n Примітка: Будь-ласка, не використовуйте депозитні адреси для обміну.",
            save: "Зберегти",
            update: "Обновити",
            email: "Адреса електронної пошти",
            changepass: "Змінити пароль",
        },
        letterWarn1: "Ваш email",
        letterWarn2: "не перевірений. Будь ласка, натисніть, щоб відправити листа.",
        letterSucc: "Лист надіслано на ваш email",
    },
    login: {
        title: "Вхід",
        notmember: "Ще не є членом?",
        forgotpass: "Забули пароль",
    },
    account: {
        terms: "Умови для токенів",
        whitepaper: "Біла книга",
    },
    forgotpass: {
        title: "Відновити пароль",
        send: "Відправити посилання для відновлення",
        newpass: "Новий пароль",
    },
    register: {
        title: "Реестер рахунку",
        check1: "Я підтверджую, що бенефіціарний власник не є громадянином США, Китаю і Гонконгу",
        check2: "Я приймаю",
        send: "Відправити",
        gotologin: "Перейти до входу в обліковий запис",
    },
    firsthome: {
        title1: "ПРИЄДНУЙТЕСЬ ДО РЕВОЛЮЦІЇ БЛОКЧЕЙН-ДОДАТКІВ",
        title2: "Перша в світі платформа для розробки ПО, що пропонує мікропослуги для блокчейн",
        doc1: "Біла книга",
        doc2: "Умови для токенів",
        status1: "WORKING MVP",
        status2: "STABLE RELEASE",
        status3: "3 YEARS OLD",
        status4: "75000+ MONTHLY DOWNLOADS",
    },
    clock: {
        title: "Розпродаж токенов",
        register: "Зареєструватися зараз",
        price: "Ціна токена",
        min: "Мінімальна покупка",
        d: "д",
        h: "г",
        m: "х",
        s: "с",
        contact: "Для приватних продажів і інших запитів, будь ласка, зв'яжіться з нами за адресою",
        contacturl: "info@squeezer.io",
    },
    lang: {
        EN: "Англійська",
        UA: "Українська",
        RU: "Російська",
    },
    header: {
        warning: "ВАЖЛИВО! Наш веб-сайт є єдиною платформою, яка має дозвіл на продаж токенов SQR. Ми ніколи не використовуємо Telegram Messenger або інші канали для проведення торгів.",
        account: "Рахунок",
        solution: "Рішення",
        features: "Особливості",
        token: "Токен",
        roadmap: "Дорожня карта",
        team: "Команда",
        careers: "Карєра",
        mvp: "MVP",
    },
    quote: {
        text: "Мені здається, що у нас не вистачає цікавих інновацій, пов'язаних з самою технологією блокчейнe. Цей проект обіцяє бути дуже цікавим, якщо він буде успішно втілений стараннями дослідної і відданою команди.",
        writer: "Ігор Каравев, радник і експерт з топ-20 ICOBench.",
    },
    benefits: {
        topik1span: "Проблеми",
        topik1: "при створенні блокчейн-додатків",
        text1: "Налаштування середовища розробки блокчейн є трудомістким процесом, при цьому важко підтримувати стабільність для тестованих версій.",
        text2: "Тисячі нових транзакцій блокчейн, як правило, будуть давати збій системи серверної частини користувача.",
        text3: "Розробники ПЗ, мало знайомі з технологією блокчейн, перед побудовою блокчейн-додатків повинні ознайомитися з кодом генезис блоку і створити складні синтаксичні аналізатори.",
        topik2span: "Squeezer",
        topik2: "рішення",
        text4: "Створити єдиний універсальний з'єднувач блокчейн, який дозволить розробникам підключатися до будь-якого блокчейну (такому, як BTC, ETH або LTC) і використовувати пісочницю для тестування додатків.",
        text5: "Додатки Squeezer засновані на мікроуслугах, що означає, що функція Автомасштаб включається за замовчуванням. Також мікропослуги підтримують автоматичне відновлення і передбачають безшумне впровадження хмарного сервісу.",
        text6: "Платформа Squeezer буде створювати і впроваджувати програми на численних етапах від GitHub або інших репозиторіїв кодів.",
    },
    capabilities: {
        maintexthead: "Основні функціональні можливості Squeezer",
        maintext: "Squeezer представляє собою платформу, яка допомагає розробникам ПО легко створювати додатки без роботи з усією інфраструктурою блокчейн. Це також потужний інструмент для забезпечення високоякісних компонентів ПО блокчейн для великих корпоративних організацій. Squeezer використовує платформи мікропослуг світового класу, такі, як AWS Lambda, Google Functions і Azure Functions.",
        tip1head: "Нульове адміністрування",
        tip1text: "Використовуйте ваш код без будь-якої тривалої попередньої настройки або необхідності подальшого управління будь-чим.",
        tip2head: "Автомасштаб",
        tip2text: "Дозвольте вашим провайдерам послуг управляти завданнями масштабування. Немає необхідності налаштовувати оповіщення або писати скрипти для збільшення або зменшення масштабу. Будьте абсолютно спокійні в періоди високого або низького трафіку.",
        tip3head: "Оплата по мірі використання",
        tip3text: "Обчислення функції як послуги (FaaS) і дистанційне керування, оплачувані на основі користування, а не заздалегідь передбаченої продуктивності. Ви можете використовувати всі ваші ресурси, не сплачуючи ні єдиного цента за час очікування.",
        tip4head: "Умови розробки",
        tip4text: "Моделюйте середу постачальника хмарних сервісів на вашому локальному комп'ютері. Немає необхідності при кожній ітерації використовувати код. Прискорте весь цикл розробки в 10 разів.",
        tip5head: "Блокчейн",
        tip5text: "Будучи воістину революційною системою, Squeezer є першою платформою, яка об'єднує міць мікропослуг з незмінністю технології блокчейн.",
        tip6head: "Токен",
        tip6text: "Токен Squeezer (SQR) є основною утилітою, використовуваною розробниками для створення і впровадження програм на Платформі Squeezer.",
    },
    facts: {
        fact1articl: "Більше 75 000 завантажень щомісяця",
        fact1text: "Наша система отримала багато позитивних відгуків на NPM, одному з кращих реєстрів програмного забезпечення.",
        fact2articl: "Більше 7000 обмінів",
        fact2text: "Наше масштабоване рішення уможливить обмін для підтримки транзакцій з великим об'ємом.",
        fact3articl: "Заплановано понад 40 мільйонів розробників",
        fact3text: "Багато розробників ПЗ кожен день працюють в середовищі технології блокчейн. Ми прагнемо зробити їх роботу максимально простою та зручною.",
    },
    connector: {
        artikle: "З'єднувач блокчейн Squeezer",
        text: "Наше рішення призначене для створення простого інтерфейсу, який дозволить розробникам ПО проводити транзакції блокчейн без необхідності використання генезис коду блокчейн або створення складних компонентів.",
        link: "Вихідний код на GitHub",
    },
    tokens: {
        artikle: "Токени Squeezer",
        text1: "Платформа Squeezer заснована на токенах SQR. Розробники купують підписку на платформу з використанням токенов для створення своїх додатків. Крім того, всі консультативні послуги, що надаються командою Squeezer, оплачуються токенами SQR.",
        text2: "Кожні 6 місяців ми будемо використовувати 25% нашого прибутку, щоб викуповувати і знищити SQR, поки ми не купимо 40% всіх SQR.",
    },
    tokeninfo: {
        head: "Детальна інформація про токени",
        infoelementfirstTicker: "Тікер:",
        infoelementfirstPrice: "Ціна:",
        infoelementfirstSoftcap: "Мінімальный поріг:",
        infoelementfirstHardcap: "Максимальне значення:",

        infoelementsecondPresale: "Предпродажа:",
        infoelementsecondPresaletext: "Попередній продаж:",
        infoelementsecondTarget: "Трав 1, 2018 - Трав 12, 2018",

        infoelementthirdTokensale: "Продаж токенів:",
        infoelementthirdTokensaletext: "червень 20, 2018 - червень 30, 2018",
        infoelementthirdTarget: "Ціль:",

        infoelementthirdCompatibility: "Сумісність:",
        infoelementthirdUsage: "Використовування:",
        infoelementthirdUsagetext: "Підписка на платформу; консультаційні послуги",
        infoelementthirdTokendeliverydate: "Дата доставки токенів:",
        infoelementthirdTokendeliverydatetext: "10 днів після завершення продажу токенів. По закінченню продажу токенів, усі непродані токени згорять.",

        distributionhead: "Розподіл токенов",
        distribution1article: "Продаж токенів:",
        distribution1text: "75,000,000 SQR (40%) По закінченню продажу токенів, усі непродані токени згорять.",
        distribution2article: "Платформа Squeezer:",
        distribution2text: "56,250,000 SQR (30%) Резерв, необхідний для забезпечення роботи платформи. Замкнено в смарт-контракті з обмеженням платежів на 12 місяців.",
        distribution3article: "Команда:",
        distribution3text: "37,500,000 SQR (20%) Замкнуто в смарт-контракті з обмеженням платежів на 24 місяці.",
        distribution4article: "Консультанти:",
        distribution4text: "9,375,000 SQR (5%) Замкнуто в смарт-контракті з обмеженням платежів на 24 місяці.",
        distribution5article: "Маркетинг и партнери:",
        distribution5text: "9,375,000 SQR (5%)",

        incomehead: "Дохід від продажу токенів",
        incometext1: "Технічна розробка:",
        incometext2: "Не технічний персонал:",
        incometext3: "Витрати на маркетинг:",
        incometext4: "Витрати на інфраструктуру:",
        incometext5: "Інші операційні витрати:",
    },
    smart: {
        artikle: "СМАРТ КОНТРАКТ",
        link1: "Вихідний код на GitHub",
        link2: "Інформація на Etherscan.io",
    },
    roadmap: {
        head: "Дорожня карта",
        roadmapdata1: "Лютий 2016",
        roadmapgoal1: "Створити загальні принципи і додати базові функціональні можливості",
        roadmapdata2: "Вересень 2016",
        roadmapgoal2: "Перевірка концепції та інтеграція модулів",
        roadmapdata3: "Жовтень 2017",
        roadmapgoal3: "Стабільна версія і постачальники хмарних сервісів",
        roadmapdata4: "Травень 2018",
        roadmapgoal4: "Етап краудфандінга попереднього продажу токенов",
        roadmapdata5: "Червень 2018",
        roadmapgoal5: "Публічний продаж токенов",
        roadmapdata6: "Липень 2018",
        roadmapgoal6: "Найняти додаткових розробників для побудови хмарних з'єднувачів блокчейн",
        roadmapdata7: "Лютий 2019",
        roadmapgoal7: "Забезпечити хмарні компоненти блокчейн і з'єднувачі",
        roadmapdata8: "Квітень 2019",
        roadmapgoal8: "Дозволити покупку підписки за допомогою токена SQR. Почніть створювати додатки, пов'язані з блокчейн",
    },
    team: {
        head1: "Консультанти",
        head2: "Команда Squeezer",
    },
    media: {
        head: "Мультимедіа",
    },
    clients: {
        head: "Партнери та клієнти",
    },
    share: {
        Sharetext: "Приєднуйтесь до нашої партнерської програми сьогодні і заробіть 10% комісії в ETH",
        Sharelink: "Приєднатися",
    },
    questions: {
        head: "Поширені запитання",
        FAQ1: "Яка користь від токена SQR всередині платформи Squeezer?",
        FAQanswer1: "Токен SQR - це паливо, яке живить енергією нашу платформу. Розробники будуть використовувати маркери для створення і впровадження блокчейн-додатків. Крім того, всі консультаційні послуги на платформі Squeezer будуть оплачуватися в токенах SQR.",
        FAQ2: "Як технологія блокчейн інтегрується в ваш продукт?",
        FAQanswer2: "Для з'єднання мікропослуг з блокчейн, ми створюємо незалежний з'єднувач, модуль, який використовується додатками для читання і запису транзакцій блокчейн, або активації інших функцій блокчейн, таких, як смарт контракти.",
        FAQ3: "Ви володієте необхідними навичками, щоб забезпечити виконання дорожньої карти?",
        FAQanswer3: "Наш виконавчий директор, Нік Чісіу, спеціалізується на мікропослугах. Він успішно завершив численні проекти в цій галузі, працюючи на американські корпорації, що входять в топ 1000. Крім того, протягом ряду років він працював консультантом по блокчейн. Він керуватиме командою розробників, гарантуючи виконання нами наших обіцянок.",
        FAQ4: "В даний час у вас є робочий продукт (MVP)?",
        FAQanswer4: "Так. Ми вже побудували систему нашої платформи, яка буде служити в якості основного інструменту, який використовується розробниками для створення, побудови, складання і впровадження своїх проектів. Блокчейн коннектор незабаром буде підключений до системи в зрозумілою конфігурації, щоб вона була максимально доступною для розробників. Ми запрошуємо вас випробувати її! Скоро ви побачите, як просто створювати і управляти проектом Squeezer на вашому локальному комп'ютері. Просто перейдіть за посиланням: https://squeezer.io/docs/getting-started/",
        link: "Для будь-яких запитів або питань щодо продажу наших токенів, звертайтеся до нас за адресою:",
    },
    endregister: {
        head1: "Не пропустіть останні новини та оновлення",
        head2: "ПРИЄДНУЙТЕСЬ ДО РЕВОЛЮЦІЇ БЛОКЧЕЙН-ДОДАТКІВ",
        button: "Підписатися",
        text1: "Програмний інтерфейс продажу токенов повністю забезпечується Системою Squeezer",
        text2: "Перша в світі платформа для розробки ПО, що пропонує мікропослуги для блокчейн",
        link1: "Увійти",
        link2: "зареєструватись",

        rejecthead: "Відмова від відповідальності",
        rejecttext1: "Токени не уявляють собою власний капітал, акції, частки, роялті або права на капітал, прибуток або дохід в платформі, ПО або організації, яка видає токени, або будь-який інший компанії або інтелектуальної власності, пов'язаної з платформою, або будь-яким іншим публічним або приватним підприємством, корпорацією, фондом або іншим юридичною особою в будь-якій юрисдикції.",
        rejecttext2: "Пропонуючи інформацію, продукти або послуги за допомогою даного веб-сайту, ми нікому не нав'язуємо використання такої інформації, продуктів або послуг в будь-якій юрисдикції, де надання такої інформації, продуктів або послуг може бути заборонено законом.",
        rejecttext3: "Вся інформація, розміщена на даному веб-сайті, призначена тільки для інформаційних цілей і може змінюватися без попереднього повідомлення. Даний веб-сайт не призначений для інвестиційних консультацій, пропозиції або рекомендації покупки або продажу будь-якого фінансового інструменту або продукту.",
        rejecttext4: "Продаж токенів Squeezer має на увазі і відноситься до розробки і використання передових і нових експериментальних технологій, які можуть не виправдати очікувань або не поставляється в комплектації, передбаченої технічною документацією.",

        footertip1: "© 2018 Squeezer",
        footertip2: "Біла Книга",
        footertip3: "Умови для токенів",
        footertip4: "Golden Data INC, New Horizon, Ground Floor, 3 1?2 Miles Philip S.W. Goldson Highway, Belize City, Belize",
    },
    errors: {
        Empty_Email: "Введіть email",
        Empty_Password: "Введіть пароль",
        Password_Not_Confirmed: "Паролі мають збігатися",
        Empty_Address: "Введіть адресу",
        Auth_Fail: "Помилкова авторизація",
        Wrong_Email_Password: "Невірний email або пароль",
        Bad_Request: "Немає з'єднання",
        Email_In_Use: "Даний email вже використовується",
        Not_Authorize: "Ви не авторизовані",
        No_Empty_Strings: "Заповніть хоча б одне поле",
        Check1: "Будь ласка, підтвердіть, що фактичний власник не є громадянином США, Китаю та Гонконгу",
        Check2: "Будь ласка, підтвердіть, що ви погоджуєтесь з Умовами токенів",
        Email_Invalid: "Невірний формат адреси",
        Pass_To_Short: "Пароль має мати більше 5 символів",
        Pass_Invalid: "Пароль має виконувати 3 з 4 умов: великі літери (A-Z), малі літери (a-z), числа (0-9) і спец символи (напр. !@#$%^&*)",
        Email_Already_Verificate: "Email уже перевірений",
        User_Dont_Exist: "Такого користувача не знайдено",
        Error_Send: "Помилка відправки листа, спробуйте ще раз",
        Email_Dont_Exist: "Цей email не використовується",
        Password_In_Use: "Це старий пароль",
        Reset_Not_Auth: "Час існування посилання закінчився. Будь ласка, надішліть новий лист",
        Letter_Error: "Будь ласка, спробуйте ще раз",
    },
    success: {
        Success_Update: "Оновлення завершене",
        Success_Eth: "Адресу Etherium оновлено",
        Success_Reset: "Пароль успішно скинуто. Тепер ви можете",
        Success_Reset_Login: "увійти",
        Success_Send_Reset: "Лист для скидання пароля надіслано",
        Success_Verify1: "Ваш email",
        Success_Verify2: "перевірено",
        Success_Send_Verify: "Лист надіслано на ваш email",
    }
}

export const RU = {
    type: "RU",
    email: "Адрес электронной почты",
    password: "Пароль",
    confirmpass: "Подтверджение пароля",
    send: "Отправить",
    profile: {
        logout: "Выйти",
        welcome: "Добро пожаловать",
        ethaddress: "Адрес ETH",
        controlPanel: {
            dashboard: "Панель управления",
            title1: "Приобретенные токены",
            text1: "Мы выдадим токены участникам на протяжении 10 дней спустя завершения Распродажи Токенов. Пожалуйста, измените настройки своего кошелька ETH (ERC20) для получения приобретенных токенов.",
            configure: "Настройка",
            title2: "Партнерская программа",
            text2: "Поделитесь вашей партнерской ссылкой и заработайте 10% в ETH на каждой покупке для пользователей, на которых вы ссылаетесь.\nОбратите внимание, что комиссия будет готова для снятия только после завершения продажи токенов.",
            affiliatelink: "Партнерская ссылка",
            registrations: "Регистрация",
            commission: "Комиссия (долл. США)",
        },
        settings: {
            settings: "Настройки",
            ethaddress: "Адрес Ethereum",
            profile: "Профиль",
            text1: "Пожалуйста, убедитесь, что у вас есть личный ключ к вашему адресу ETH. Наш токен полностью совместим с кошельками MyEtherWallet.com, Metamask или Mist.\n\nПримечание: Пожалуйста, не используйте депозитные адреса для обменных операций.",
            save: "Сохранить",
            update: "Обновить",
            email: "Адрес электронной почты",
            changepass: "Сменить пароль",
        },
        letterWarn1: "Ваш email",
        letterWarn2: "не проверен. Пожалуйста, нажмите, что бы отправить письмо.",
        letterSucc: "Письмо отправлено на ваш email",
    },
    login: {
        title: "Вход",
        notmember: "Еще не є членом?",
        forgotpass: "Забыл свой пароль",
    },
    account: {
        terms: "Условия для токенов",
        whitepaper: "Белая книга",
    },
    forgotpass: {
        title: "Восстановить пароль",
        send: "Отправить ссылку для востановления",
        newpass: "Новый пароль",
    },
    register: {
        title: "Реестр счета",
        check1: "Я подтверждаю, что бенефициарный владелец не является гражданином США, Китая и Гонконга",
        check2: "Я принимаю",
        send: "Отправить",
        gotologin: "Перейти ко входу в учетную запись",
    },
    firsthome: {
        title1: "ПРИСОЕДИНЯЙТЕСЬ К РЕВОЛЮЦИИ БЛОКЧЕЙН-ПРИЛОЖЕНИЙ",
        title2: "Первая в мире платформа для разработки ПО, предлагающая микроуслуги для блокчейн",
        doc1: "Белая бумага",
        doc2: "Условия для токенов",
        status1: "WORKING MVP",
        status2: "STABLE RELEASE",
        status3: "3 YEARS OLD",
        status4: "75000+ MONTHLY DOWNLOADS",
    },
    clock: {
        title: "Розпродажа токенов",
        register: "Зарегистрироваться сейчас",
        price: "Цена токена",
        min: "Минимальная покупка",
        d: "д",
        h: "ч",
        m: "м",
        s: "с",
        contact: "Для частных продаж и других запросов, пожалуйста, свяжитесь с нами по адресу",
        contacturl: "info@squeezer.io",
    },
    lang: {
        EN: "английский",
        UA: "украинский",
        RU: "русский",
    },
    header: {
        warning: "ВАЖНО! Наш веб-сайт является единственной платформой, имеющей разрешение на продажу токенов SQR. Мы никогда не используем Telegram Messenger или другие каналы для проведения торгов.",
        account: "Счет",
        solution: "Решение",
        features: "Черты",
        token: "Токен",
        roadmap: "Дорожная карта",
        team: "Команда",
        careers: "Карьера",
        mvp: "MVP",
    },
    quote: {
        text: "Мне кажется, что у нас не хватает интересных инноваций, связанных с самой технологией блокчейна. Этот проект обещает быть очень интересным, если он будет успешно воплощен стараниями опытной и преданной команды.",
        writer: "Игорь Каравев, советник и эксперт из топ-20 ICOBench.",
    },
    benefits: {
        topik1span: "Проблемы",
        topik1: "при создании блокчейн-приложений",
        text1: "Настройка среды разработки блокчейн является трудоемким процессом, при этом трудно поддерживать стабильность для тестируемых версий.",
        text2: "Тысячи новых транзакций блокчейн, как правило, будут давать сбой системы серверной части пользователя.",
        text3: "Разработчики ПО, мало знакомые с технологией блокчейн, перед построением блокчейн-приложений должны ознакомиться с кодом генезис блока и создать сложные синтаксические анализаторы.",
        topik2span: "Squeezer",
        topik2: "Решение",
        text4: "Создать единый универсальный соединитель блокчейн, который позволит разработчикам подключаться к любому блокчейну (такому, как BTC, ETH или LTC) и использовать песочницу для тестирования приложений.",
        text5: "Приложения Squeezer основаны на микроуслугах, что означает, что функция автомасштаба включается по умолчанию. Также микроуслуги поддерживают автоматическое восстановление и предусматривают бесшумное внедрение облачного сервиса.",
        text6: "Платформа Squeezer будет создавать и внедрять приложения на многочисленных этапах от GitHub или других репозиториев кодов.",
    },
    capabilities: {
        maintexthead: "Основные функциональные возможности Squeezer",
        maintext: "Squeezer представляет собой платформу, которая помогает разработчикам ПО легко создавать приложения без работы со всей инфраструктурой блокчейн. Это также мощный инструмент для обеспечения высококачественных компонентов ПО блокчейн для крупных корпоративных организаций. Squeezer использует платформы микроуслуг мирового класса, такие, как AWS Lambda, Google Functions и Azure Functions.",
        tip1head: "Нулевое администрирование",
        tip1text: "Используйте ваш код без какой-либо продолжительной предварительной настройки или необходимости последующего управления чем-либо.",
        tip2head: "Автомасштаб",
        tip2text: "Позвольте вашим провайдерам услуг управлять задачами масштабирования. Нет необходимости настраивать оповещения или писать скрипты для увеличения или уменьшения масштаба. Будьте абсолютно спокойны в периоды высокого или низкого трафика.",
        tip3head: "Оплата по мере использования",
        tip3text: "Вычисления функции как услуги (FaaS) и удаленное управление, оплачиваемые на основе пользования, а не заранее предусмотренной производительности. Вы можете использовать все ваши ресурсы, не платя ни единого цента за время ожидания.",
        tip4head: "Условия разработки",
        tip4text: "Моделируйте среду поставщика облачных сервисов на вашем локальном компьютере. Нет необходимости при каждой итерации использовать код. Ускорьте весь цикл разработки в 10 раз.",
        tip5head: "Блокчейн",
        tip5text: "Будучи поистине революционной системой, Squeezer является первой платформой, которая объединяет мощь микроуслуг с неизменностью технологии блокчейн.",
        tip6head: "Токен",
        tip6text: "Токен Squeezer (SQR) является основной утилитой, используемой разработчиками для создания и внедрения приложений на Платформе Squeezer.",
    },
    facts: {
        fact1articl: "Более 75 000 загрузок ежемесячно",
        fact1text: "Наша система получила много благосклонного внимания на NPM, одном из лучших реестров программного обеспечения.",
        fact2articl: "Более 7000 обменов",
        fact2text: "Наше масштабируемое решение сделает возможным обмен для поддержки транзакций с большим объемом.",
        fact3articl: "Запланировано более 40 миллионов разработчиков",
        fact3text: "Многие разработчики ПО каждый день работают в среде технологии блокчейн. Мы стремимся сделать их работу максимально простой и удобной.",
    },
    connector: {
        artikle: "Соединитель блокчейн Squeezer",
        text: "Наше решение предназначено для создания простого интерфейса, который позволит разработчикам ПО проводить транзакции блокчейн без необходимости использования генезис кода блокчейн или создания сложных компонентов.",
        link: "Исходный код на GitHub",
    },
    tokens: {
        artikle: "Токены Squeezer",
        text1: "Платформа Squeezer основана на токенах SQR. Разработчики покупают подписку на платформу с использованием токенов для создания своих приложений. Кроме того, все консультативные услуги, предоставляемые командой Squeezer, оплачиваются токенами SQR.",
        text2: "Каждые 6 месяцев мы будем использовать 25% нашей прибыли, чтобы выкупать и уничтожить SQR, пока мы не купим 40% всех SQR.",
    },
    tokeninfo: {
        head: "Подробная информация о токенах",
        infoelementfirstTicker: "Тикер:",
        infoelementfirstPrice: "Цена:",
        infoelementfirstSoftcap: "Минимальный предел:",
        infoelementfirstHardcap: "Максимальное значение:",

        infoelementsecondPresale: "Предпродажа:",
        infoelementsecondPresaletext: "Май 1, 2018 - Май 12, 2018",
        infoelementsecondTarget: "Цель:",

        infoelementthirdTokensale: "Продажа токенов:",
        infoelementthirdTokensaletext: "Июнь 20, 2018 - Июнь 30, 2018",
        infoelementthirdTarget: "Цель:",

        infoelementthirdCompatibility: "Совместимость:",
        infoelementthirdUsage: "Использование:",
        infoelementthirdUsagetext: "Подписка на платформу; консультационные услуги",
        infoelementthirdTokendeliverydate: "Дата доставки токенов:",
        infoelementthirdTokendeliverydatetext: "10 дней после завершения продажи токенов\nПо окончании продажи токенов, все непроданные токены сгорят.",

        distributionhead: "Распределение токенов",
        distribution1article: "Продажа токенов:",
        distribution1text: "75,000,000 SQR (40%) По окончании продажи токенов, все непроданные токены сгорят.",
        distribution2article: "Платформа Squeezer:",
        distribution2text: "56,250,000 SQR (30%) Резерв, требуемый для обеспечения работы платформы. Заперто в смарт-контракте с ограничением платежей на 12 месяцев.",
        distribution3article: "Команда:",
        distribution3text: "37,500,000 SQR (20%) Заперто в смарт-контракте с ограничением платежей на 24 месяца.",
        distribution4article: "Консультанты:",
        distribution4text: "9,375,000 SQR (5%) Заперто в смарт-контракте с ограничением платежей на 24 месяца.",
        distribution5article: "Маркетинг и партнеры:",
        distribution5text: "9,375,000 SQR (5%)",

        incomehead: "Доход от продажи токенов",
        incometext1: "Техническая разработка:",
        incometext2: "Не технический персонал: ",
        incometext3: "Расходы на маркетинг: ",
        incometext4: "Расходы на инфраструктуру: ",
        incometext5: "Другие операционные расходы: ",
    },
    smart: {
        artikle: "СМАРТ КОНТРАКТ",
        link1: "Исходный код на GitHub",
        link2: "Информация на Etherscan.io",
    },
    roadmap: {
        head: "Дорожная карта",
        roadmapdata1: "Февраль 2016",
        roadmapgoal1: "Создать общие принципы и добавить базовые функциональные возможности",
        roadmapdata2: "Сентябрь 2016",
        roadmapgoal2: "Проверка концепции и интеграция подключаемых модулей",
        roadmapdata3: "Октябрь 2017",
        roadmapgoal3: "Стабильная версия и поставщики облачных сервисов",
        roadmapdata4: "Май 2018",
        roadmapgoal4: "Этап краудфандинга предпродажи токенов",
        roadmapdata5: "Июнь 2018",
        roadmapgoal5: "Публичная продажа токенов",
        roadmapdata6: "Июль 2018",
        roadmapgoal6: "Нанять дополнительных разработчиков для построения облачных соединителей блокчейн",
        roadmapdata7: "Февраль 2019",
        roadmapgoal7: "Обеспечить облачные компоненты блокчейн и соединители",
        roadmapdata8: "Апрель 2019",
        roadmapgoal8: "Разрешить покупку подписки с помощью токена SQR. Начните создавать приложения, связанные с блокчейн",
    },
    team: {
        head1: "Консультанты",
        head2: "Команда Squeezer",
    },
    media: {
        head: "Мультимедиа",
    },
    clients: {
        head: "Партнеры и клиенты",
    },
    share: {
        Sharetext: "Присоединяйтесь к нашей Партнерской программе сегодня и заработайте 10% комиссии в ETH",
        Sharelink: "Присоединиться",
    },
    questions: {
        head: "Часто задаваемые вопросы",
        FAQ1: "Какая польза от токена SQR внутри платформы Squeezer?",
        FAQanswer1: "Токен SQR - это топливо, которое питает энергией нашу платформу. Разработчики будут использовать токены для создания и внедрения блокчейн-приложений. Кроме того, все консультационные услуги на платформе Squeezer будут оплачиваться в токенах SQR.",
        FAQ2: "Как технология блокчейн интегрируется в ваш продукт?",
        FAQanswer2: "Для соединения микроуслуг с блокчейн, мы создаем независимый соединитель, модуль, который используется приложениями для чтения и записи транзакций блокчейн, либо активации других функций блокчейн, таких, как смарт контракты.",
        FAQ3: "Вы обладаете необходимыми навыками, чтобы обеспечить выполнение дорожной карты?",
        FAQanswer3: "Наш исполнительный директор, Ник Чисиу, специализируется на микроуслугах. Он успешно завершил многочисленные проекты в этой области, работая на американские корпорации, входящие в топ 1000. Кроме того, на протяжении ряда лет он работал консультантом по блокчейн. Он будет руководить командой разработчиков, гарантируя выполнение нами наших обещаний.",
        FAQ4: "В настоящее время у вас имеется рабочий продукт (MVP)?",
        FAQanswer4: "Да. Мы уже построили систему нашей платформы, которая будет служить в качестве основного инструмента, который используют разработчики для создания, построения, составления и внедрения своих проектов. Блокчейн коннектор вскоре будет подключен к системе в понятной конфигурации, чтобы она была максимально доступной для разработчиков. Мы приглашаем вас опробовать ее! Скоро вы увидите, как просто создавать и управлять проектом Squeezer на вашем локальном компьютере. Просто перейдите по ссылке: https://squeezer.io/docs/getting-started/",
        link: "Для любых запросов или вопросов относительно продажи наших токенов, обращайтесь к нам по адресу:",
    },
    endregister: {
        head1: "Не пропустите последние новости и обновления",
        head2: "ПРИСОЕДИНЯЙТЕСЬ К РЕВОЛЮЦИИ БЛОКЧЕЙН-ПРИЛОЖЕНИЙ",
        button: "Подписаться",
        text1: "Программный интерфейс продажи токенов полностью обеспечивается Системой Squeezer",
        text2: "Первая в мире платформа для разработки ПО, предлагающая микроуслуги для блокчейн",
        link1: "Войти",
        link2: "Зарегистрироватся",

        rejecthead: "Отказ от ответственности",
        rejecttext1: "Токены не представляют собой собственный капитал, акции, доли, роялти или права на капитал, прибыль или доход в платформе, ПО или организации, выдающей токены, либо любой другой компании или интеллектуальной собственности, связанной с платформой, либо любым другим публичным или частным предприятием, корпорацией, фондом или иным юридическим лицом в любой юрисдикции.",
        rejecttext2: "Предлагая информацию, продукты или услуги посредством данного веб-сайта, мы никому не навязываем использование такой информации, продуктов или услуг в какой-либо юрисдикции, где предоставление такой информации, продуктов или услуг может быть запрещено законом.",
        rejecttext3: "Вся информация, представленная на данном веб-сайте, предназначена только для информационных целей и может изменяться без уведомления. Данный веб-сайт не предназначен для инвестиционных консультаций, предложения или рекомендации покупки или продажи какого-либо финансового инструмента или продукта.",
        rejecttext4: "Продажа токенов Squeezer подразумевает и относится к разработке и использованию передовых и новых экспериментальных технологий, которые могут не оправдать ожиданий или не поставляться в комплектации, предусмотренной технической документацией.",

        footertip1: "© 2018 Squeezer",
        footertip2: "Белая Бумага",
        footertip3: "Условия для токенов",
        footertip4: "Golden Data INC, New Horizon, Ground Floor, 3 1⁄2 Miles Philip S.W. Goldson Highway, Belize City, Belize",
    },
    errors: {
        Empty_Email: "Введите email",
        Empty_Password: "Введите пароль",
        Password_Not_Confirmed: "Пароли должны совпадать",
        Empty_Address: "Введите адрес",
        Auth_Fail: "Ошибка авторизации",
        Wrong_Email_Password: "Неверный email или пароль",
        Bad_Request: "Нет соединения",
        Email_In_Use: "Такой email уже используется",
        Not_Authorize: "Нужна авторизация",
        No_Empty_Strings: "Нужно ввести хотя б одно поле",
        Check1: "Пожалуйста, подтвердите, что фактический владелец не является гражданином США, Китая и Гонконга",
        Check2: "Пожалуйста, подтвердите, что вы согласны с Условиями токенов",
        Email_Invalid: "Неверный формат адреса",
        Pass_To_Short: "Пароль должен иметь больше 5 символов",
        Pass_Invalid: "Пароль должен выполнять 3 из 4 условий: большие буквы (A-Z), строчные буквы (a-z), числа (0-9) и спец символы (напр. !@#$%^&*)",
        Email_Already_Verificate: "Email уже проверено",
        User_Dont_Exist: "Такого пользователя не найдено",
        Error_Send: "Ошибка отправки письма, попробуйте еще раз",
        Email_Dont_Exist: "Этот email уже используется",
        Password_In_Use: "Это старый пароль",
        Reset_Not_Auth: "Время существования ссылки закончилось. Пожалуйста, пришлите новое письмо",
        Letter_Error: "Пожалуйста, попробуйте еще раз",
    },
    success: {
        Success_Update: "Обновление завершено",
        Success_Eth: "Адрес Etherium был обновлен",
        Success_Reset: "Сброс пароля произошел успешно. Теперь вы можете",
        Success_Reset_Login: "войти",
        Success_Send_Reset: "Письмо для сброса пароля отправлено",
        Success_Verify1: "Ваш email",
        Success_Verify2: "проверен",
        Success_Send_Verify: "Письмо отрпавлено на ваш email",
    }
}